#include "Hooks.h"
#include "Menu.h"
#include "Settings.h"

namespace Plugin
{
	inline constexpr auto NAME = "StepUpOntoSKSE"sv;
}

namespace
{
	void InitializeLog()
	{
		auto path = logger::log_directory();
		if (!path) {
			stl::report_and_fail("Failed to find standard logging directory"sv);
		}
		*path /= (std::string{ Plugin::NAME } + ".log");
		auto sink = std::make_shared<spdlog::sinks::basic_file_sink_mt>(path->string(), true);
		auto log = std::make_shared<spdlog::logger>("global log"s, std::move(sink));
		log->set_level(spdlog::level::debug);
		log->flush_on(spdlog::level::debug);
		spdlog::set_default_logger(std::move(log));
		spdlog::set_pattern("[%H:%M:%S] [%l] %v"s);
	}

	void MessageHandler(SKSE::MessagingInterface::Message* a_msg)
	{
		if (!a_msg) {
			return;
		}
		switch (a_msg->type) {
		case SKSE::MessagingInterface::kDataLoaded:
			Settings::GetSingleton()->Load();
			Hooks::Install();
			Menu::Register();
			logger::info("{} initialized", Plugin::NAME);
			break;
		case SKSE::MessagingInterface::kPostLoadGame:
		case SKSE::MessagingInterface::kNewGame:
			Settings::GetSingleton()->Load();
			break;
		default:
			break;
		}
	}
}

// Normally generated by add_commonlibsse_plugin; declared manually in this build.
SKSEPluginInfo(
	.Version = REL::Version{ 1, 5, 1 },
	.Name = "StepUpOntoSKSE"sv,
	.Author = ""sv,
	.StructCompatibility = SKSE::StructCompatibility::Independent,
	.RuntimeCompatibility = SKSE::VersionIndependence::AddressLibrary)

SKSEPluginLoad(const SKSE::LoadInterface* a_skse)
{
	InitializeLog();
	logger::info("{} loading", Plugin::NAME);

	SKSE::Init(a_skse);

	auto* messaging = SKSE::GetMessagingInterface();
	if (!messaging->RegisterListener(MessageHandler)) {
		logger::error("Failed to register messaging listener");
		return false;
	}

	return true;
}
